<?php
$formSuccess='';$formError='';$formName='';$formPhone='';$formEmail='';$formMessage='';
if(isset($_GET['sent'])&&$_GET['sent']==='1'){$formSuccess='Uw klacht is succesvol verzonden.';}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $formName=isset($_POST['name'])?trim($_POST['name']):'';$formPhone=isset($_POST['phone'])?trim($_POST['phone']):'';$formEmail=isset($_POST['email'])?trim($_POST['email']):'';$formMessage=isset($_POST['message'])?trim($_POST['message']):'';
  if($formName===''||$formEmail===''||$formMessage===''){$formError='Vul alle verplichte velden in.';}elseif(!filter_var($formEmail,FILTER_VALIDATE_EMAIL)){$formError='Vul een geldig e-mailadres in.';}elseif(!function_exists('curl_init')){$formError='De klacht kon niet worden verzonden. Probeer het later opnieuw.';error_log('Complaint API error: cURL is not available.');}else{
    $domain=isset($_SERVER['SERVER_NAME'])?$_SERVER['SERVER_NAME']:'';if($domain===''&&isset($_SERVER['HTTP_HOST'])){$domain=$_SERVER['HTTP_HOST'];}$domain=preg_replace('/:\d+$/','',$domain);
    $payload=['domain'=>$domain,'page'=>'complain','name'=>$formName,'phone'=>$formPhone,'email'=>$formEmail,'message'=>$formMessage];
    $curl=curl_init('https://zzpzo.net/api/v1/insertuserscontactform');curl_setopt_array($curl,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($payload),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded'],CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>15]);
    $apiResponse=curl_exec($curl);$httpCode=curl_getinfo($curl,CURLINFO_HTTP_CODE);$curlError=curl_error($curl);curl_close($curl);
    if($curlError===''&&$httpCode>=200&&$httpCode<300){header('Location: complain.php?sent=1#form-feedback');exit;}
    $formError='De klacht kon niet worden verzonden. Probeer het later opnieuw.';error_log('Complaint API error. HTTP: '.$httpCode.' Curl: '.$curlError.' Response: '.$apiResponse);
  }
}
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php $filePath='title.txt';if(file_exists($filePath)){echo nl2br(htmlspecialchars(file_get_contents($filePath)));}else{echo 'Titel';} ?> - Klachtenportaal</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400"><link rel="stylesheet" href="css/fontawesome-all.min.css?id=<?php echo filemtime('css/fontawesome-all.min.css'); ?>"><link rel="stylesheet" href="css/bootstrap.min.css?id=<?php echo filemtime('css/bootstrap.min.css'); ?>"><link rel="stylesheet" href="css/magnific-popup.css?id=<?php echo filemtime('css/magnific-popup.css'); ?>"><link rel="stylesheet" href="slick/slick.css?id=<?php echo filemtime('slick/slick.css'); ?>"><link rel="stylesheet" href="slick/slick-theme.css?id=<?php echo filemtime('slick/slick-theme.css'); ?>"><link rel="stylesheet" href="css/tooplate-style.css?id=<?php echo filemtime('css/tooplate-style.css'); ?>">
<style>.zz-form-feedback{margin:0 0 1.25rem;padding:.9rem 1rem;border:1px solid transparent;border-radius:4px;line-height:1.5;text-align:left;overflow-wrap:anywhere;scroll-margin-top:7rem}.zz-form-feedback-success{color:#155724;background:#d4edda;border-color:#c3e6cb}.zz-form-feedback-error{color:#721c24;background:#f8d7da;border-color:#f5c6cb}.zz-dynamic-content{max-width:100%;box-sizing:border-box;overflow-wrap:anywhere;word-break:break-word;overflow-x:hidden}@media(max-width:767px){.tm-address-box,.zz-dynamic-content{height:auto!important;min-height:0!important;max-height:none!important;overflow:visible!important}}</style>
</head>
<body style="background-image:url('img/constructive_bg_04.jpg');"><div class="zz-page-shell"><div class="container-fluid tm-main"><div class="row tm-main-row">
<div id="tmSideBar" class="col-xl-3 col-lg-4 col-md-12 col-sm-12 sidebar"><button id="tmMainNavToggle" class="menu-icon">&#9776;</button><div class="inner"><a href="index.php" class="navbar-brand" id="brandLogo"><img src="logo.png?id=<?php echo filemtime('logo.png'); ?>" alt="Logo" onerror="this.remove();"></a><nav id="tmMainNav" class="tm-main-nav"><ul><li><a href="index.php"><i class="fas fa-home tm-nav-fa-icon"></i><span>Startpagina</span></a></li><li><a href="about.php"><i class="fas fa-info-circle tm-nav-fa-icon"></i><span>Over ons</span></a></li><li><a href="service.php"><i class="fas fa-map tm-nav-fa-icon"></i><span>Diensten</span></a></li><li><a href="contact.php"><i class="fas fa-comments tm-nav-fa-icon"></i><span>Contact</span></a></li></ul></nav></div></div>
<div class="col-xl-9 col-lg-8 col-md-12 col-sm-12 tm-content"><section class="tm-section zz-form-box"><div class="tm-bg-transparent-black tm-contact-box-pad"><div class="row mb-4"><div class="col-sm-12"><header><h2 class="tm-text-shadow">Klachtenportaal</h2></header></div></div><div class="row tm-page-4-content">
<div class="col-md-6 col-sm-12 tm-contact-col"><div class="tm-address-box zz-dynamic-content text-content"><?php $filePath='complain.txt';if(file_exists($filePath)){echo nl2br(htmlspecialchars(file_get_contents($filePath)));}else{echo '-';} ?></div></div>
<div class="col-md-6 col-sm-12 tm-contact-col"><div class="contact_message">
<?php if($formSuccess!==''): ?><div id="form-feedback" class="zz-form-feedback zz-form-feedback-success" role="status" aria-live="polite"><?php echo htmlspecialchars($formSuccess); ?></div><?php endif; ?><?php if($formError!==''): ?><div id="form-feedback" class="zz-form-feedback zz-form-feedback-error" role="alert"><?php echo htmlspecialchars($formError); ?></div><?php endif; ?>
<form action="" method="post" class="contact-form"><div class="form-group"><input type="text" name="name" class="form-control" placeholder="Naam" value="<?php echo htmlspecialchars($formName,ENT_QUOTES,'UTF-8'); ?>" maxlength="150" autocomplete="name" required></div><div class="form-group"><input type="text" name="phone" class="form-control" placeholder="Telefoon" value="<?php echo htmlspecialchars($formPhone,ENT_QUOTES,'UTF-8'); ?>" maxlength="50" autocomplete="tel"></div><div class="form-group"><input type="email" name="email" class="form-control" placeholder="E-mail" value="<?php echo htmlspecialchars($formEmail,ENT_QUOTES,'UTF-8'); ?>" maxlength="254" autocomplete="email" required></div><div class="form-group"><textarea name="message" class="form-control" rows="9" placeholder="Bericht" maxlength="5000" required><?php echo htmlspecialchars($formMessage); ?></textarea></div><button type="submit" class="btn tm-btn-submit tm-btn">Verzenden</button></form>
</div></div><div class="zz-form-note">Deze site wordt beschermd door reCAPTCHA. Het <a href="privacy.php">privacybeleid</a> en de <a href="terms.php">algemene voorwaarden</a> van Google zijn van toepassing.</div>
</div></div></section></div>
<footer class="footer-link"><div class="tm-copyright-text"><p>Auteursrecht &copy; <?php echo date('Y'); ?> ZZpzo</p></div><div class="zz-footer-links"><a href="terms.php">Algemene voorwaarden</a><a href="complain.php">Klachtenportaal</a><a href="privacy.php">Privacybeleid</a></div></footer>
</div></div>
<script src="js/jquery-3.2.1.min.js?id=<?php echo filemtime('js/jquery-3.2.1.min.js'); ?>"></script><script src="js/jquery.magnific-popup.min.js?id=<?php echo filemtime('js/jquery.magnific-popup.min.js'); ?>"></script><script src="slick/slick.min.js?id=<?php echo filemtime('slick/slick.min.js'); ?>"></script><script src="js/zz-dynamic.js?id=<?php echo filemtime('js/zz-dynamic.js'); ?>"></script><script>(function(){window.addEventListener('load',function(){var f=document.getElementById('form-feedback');if(f){setTimeout(function(){f.scrollIntoView({behavior:'smooth',block:'center'});},220);}});})();</script>
</div></body></html>