<?php
$formSuccess='';$formError='';$formName='';$formPhone='';$formEmail='';$formMessage='';
if(isset($_GET['sent'])&&$_GET['sent']==='1'){$formSuccess='Uw bericht is succesvol verzonden.';}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $formName=isset($_POST['name'])?trim($_POST['name']):'';$formPhone=isset($_POST['phone'])?trim($_POST['phone']):'';$formEmail=isset($_POST['email'])?trim($_POST['email']):'';$formMessage=isset($_POST['message'])?trim($_POST['message']):'';
  if($formName===''||$formEmail===''||$formMessage===''){$formError='Vul alle verplichte velden in.';}elseif(!filter_var($formEmail,FILTER_VALIDATE_EMAIL)){$formError='Vul een geldig e-mailadres in.';}elseif(!function_exists('curl_init')){$formError='Het bericht kon niet worden verzonden. Probeer het later opnieuw.';error_log('Contact API error: cURL is not available.');}else{
    $domain=isset($_SERVER['SERVER_NAME'])?$_SERVER['SERVER_NAME']:'';if($domain===''&&isset($_SERVER['HTTP_HOST'])){$domain=$_SERVER['HTTP_HOST'];}$domain=preg_replace('/:\d+$/','',$domain);
    $payload=['domain'=>$domain,'page'=>'contact','name'=>$formName,'phone'=>$formPhone,'email'=>$formEmail,'message'=>$formMessage];
    $curl=curl_init('https://zzpzo.net/api/v1/insertuserscontactform');curl_setopt_array($curl,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($payload),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded'],CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>15]);
    $apiResponse=curl_exec($curl);$httpCode=curl_getinfo($curl,CURLINFO_HTTP_CODE);$curlError=curl_error($curl);curl_close($curl);
    if($curlError===''&&$httpCode>=200&&$httpCode<300){header('Location: contact.php?sent=1#form-feedback');exit;}
    $formError='Het bericht kon niet worden verzonden. Probeer het later opnieuw.';error_log('Contact API error. HTTP: '.$httpCode.' Curl: '.$curlError.' Response: '.$apiResponse);
  }
}
?>
<!DOCTYPE html>
<html lang="nl">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?php $filePath='title.txt';if(file_exists($filePath)){echo nl2br(htmlspecialchars(file_get_contents($filePath)));}else{echo 'Titel';} ?> - Contact</title><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600"><link rel="stylesheet" href="css/bootstrap.min.css?id=<?php echo filemtime('css/bootstrap.min.css'); ?>"><link rel="stylesheet" href="slick/slick.css?id=<?php echo filemtime('slick/slick.css'); ?>"><link rel="stylesheet" href="slick/slick-theme.css?id=<?php echo filemtime('slick/slick-theme.css'); ?>"><link rel="stylesheet" href="css/magnific-popup.css?id=<?php echo filemtime('css/magnific-popup.css'); ?>"><link rel="stylesheet" href="css/tooplate-style.css?id=<?php echo filemtime('css/tooplate-style.css'); ?>"><link rel="stylesheet" href="css/zz-layout-fix.css?id=<?php echo filemtime('css/zz-layout-fix.css'); ?>"><style>.zz-form-feedback{margin:0 0 1.25rem;padding:.9rem 1rem;border:1px solid transparent;border-radius:4px;line-height:1.5;text-align:left;overflow-wrap:anywhere;scroll-margin-top:7rem}.zz-form-feedback-success{color:#155724;background:#d4edda;border-color:#c3e6cb}.zz-form-feedback-error{color:#721c24;background:#f8d7da;border-color:#f5c6cb}.zz-dynamic-content{max-width:100%;box-sizing:border-box;overflow-wrap:anywhere;word-break:break-word;overflow-x:hidden}@media(max-width:767px){.zz-contact-info,.zz-dynamic-content{height:auto!important;min-height:0!important;max-height:none!important;overflow:visible!important}}</style></head>
<?php $defaultBanner="img/photo-05.jpg";$bannerFile="contactimage.txt";if(file_exists($bannerFile)){$bannerUrl=trim(file_get_contents($bannerFile));if($bannerUrl===""){$bannerUrl=$defaultBanner;}}else{$bannerUrl=$defaultBanner;} ?>
<body class="zz-page" style="background-image:url('<?php echo htmlspecialchars($bannerUrl); ?>');"><div class="tm-main-container"><div class="tm-top-container"><nav id="tmNav" class="tm-nav"><a class="tm-navbar-menu" href="#">Menu</a><ul class="tm-nav-links"><li class="tm-nav-item"><a href="index.php" class="tm-nav-link">Startpagina</a></li><li class="tm-nav-item"><a href="about.php" class="tm-nav-link">Over ons</a></li><li class="tm-nav-item"><a href="service.php" class="tm-nav-link">Diensten</a></li><li class="tm-nav-item active"><a href="contact.php" class="tm-nav-link">Contact</a></li></ul></nav><div style="background-color:rgba(0,0,0,.62);padding:10px 20px;"><a href="index.php" id="brandLogo"><img src="logo.png?id=<?php echo filemtime('logo.png'); ?>" alt="Logo" onerror="this.remove();"></a></div></div>
<main class="zz-main-content"><section class="zz-contact-layout"><div class="tm-bg-dark zz-contact-info zz-dynamic-content text-content"><h2>Contact</h2><?php $filePath='contact.txt';if(file_exists($filePath)){echo nl2br(htmlspecialchars(file_get_contents($filePath)));}else{echo '-';} ?></div><div>
<?php if($formSuccess!==''): ?><div id="form-feedback" class="zz-form-feedback zz-form-feedback-success" role="status" aria-live="polite"><?php echo htmlspecialchars($formSuccess); ?></div><?php endif; ?><?php if($formError!==''): ?><div id="form-feedback" class="zz-form-feedback zz-form-feedback-error" role="alert"><?php echo htmlspecialchars($formError); ?></div><?php endif; ?>
<form action="" class="tm-contact-form" method="post"><div class="form-group mb-4"><input type="text" name="name" class="form-control" placeholder="Naam" value="<?php echo htmlspecialchars($formName,ENT_QUOTES,'UTF-8'); ?>" maxlength="150" autocomplete="name" required></div><div class="form-group mb-4"><input type="text" name="phone" class="form-control" placeholder="Telefoon" value="<?php echo htmlspecialchars($formPhone,ENT_QUOTES,'UTF-8'); ?>" maxlength="50" autocomplete="tel"></div><div class="form-group mb-4"><input type="email" name="email" class="form-control" placeholder="E-mail" value="<?php echo htmlspecialchars($formEmail,ENT_QUOTES,'UTF-8'); ?>" maxlength="254" autocomplete="email" required></div><div class="form-group mb-4"><textarea rows="4" name="message" class="form-control" placeholder="Bericht" maxlength="5000" required><?php echo htmlspecialchars($formMessage); ?></textarea></div><div class="form-group mb-0"><button type="submit" class="btn tm-send-btn tm-fl-right">Verzenden</button></div><div class="zz-contact-note">Deze site wordt beschermd door reCAPTCHA. Het <a href="privacy.php">privacybeleid</a> en de <a href="terms.php">algemene voorwaarden</a> van Google zijn van toepassing.</div></form>
</div></section></main>
<div class="zz-bottom-container"><footer class="zz-footer"><p>Auteursrecht &copy; <?php echo date('Y'); ?> ZZpzo</p><div class="zz-footer-links"><a href="terms.php">Algemene voorwaarden</a><a href="complain.php">Klachtenportaal</a><a href="privacy.php">Privacybeleid</a></div></footer></div></div>
<script src="js/jquery-1.11.0.min.js?id=<?php echo filemtime('js/jquery-1.11.0.min.js'); ?>"></script><script>window.onload=function(){document.body.classList.add('loaded');var f=document.getElementById('form-feedback');if(f){setTimeout(function(){f.scrollIntoView({behavior:'smooth',block:'center'});},220);}};document.addEventListener('DOMContentLoaded',function(){var menu=document.querySelector('.tm-navbar-menu');var links=document.querySelector('.tm-nav-links');if(menu&&links){menu.addEventListener('click',function(e){e.preventDefault();links.classList.toggle('open');links.style.display=links.classList.contains('open')?'flex':'none';});window.addEventListener('resize',function(){if(window.innerWidth>991){links.classList.add('open');links.style.removeProperty('display');}});}});</script>
</body></html>