<?php
$formSuccess='';$formError='';$formName='';$formPhone='';$formEmail='';$formMessage='';
if(isset($_GET['sent'])&&$_GET['sent']==='1'){$formSuccess='Uw bericht is succesvol verzonden.';}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $formName=isset($_POST['name'])?trim($_POST['name']):'';$formPhone=isset($_POST['phone'])?trim($_POST['phone']):'';$formEmail=isset($_POST['email'])?trim($_POST['email']):'';$formMessage=isset($_POST['message'])?trim($_POST['message']):'';
  if($formName===''||$formEmail===''||$formMessage===''){$formError='Vul alle verplichte velden in.';}elseif(!filter_var($formEmail,FILTER_VALIDATE_EMAIL)){$formError='Vul een geldig e-mailadres in.';}elseif(!function_exists('curl_init')){$formError='Het bericht kon niet worden verzonden. Probeer het later opnieuw.';error_log('Contact API error: cURL is not available.');}else{
    $domain=isset($_SERVER['SERVER_NAME'])?$_SERVER['SERVER_NAME']:'';if($domain===''&&isset($_SERVER['HTTP_HOST'])){$domain=$_SERVER['HTTP_HOST'];}$domain=preg_replace('/:\d+$/','',$domain);
    $payload=['domain'=>$domain,'page'=>'contact','name'=>$formName,'phone'=>$formPhone,'email'=>$formEmail,'message'=>$formMessage];
    $curl=curl_init('https://zzpzo.net/api/v1/insertuserscontactform');curl_setopt_array($curl,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($payload),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded'],CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>15]);
    $apiResponse=curl_exec($curl);$httpCode=curl_getinfo($curl,CURLINFO_HTTP_CODE);$curlError=curl_error($curl);curl_close($curl);
    if($curlError===''&&$httpCode>=200&&$httpCode<300){header('Location: contact.php?sent=1#form-feedback');exit;}
    $formError='Het bericht kon niet worden verzonden. Probeer het later opnieuw.';error_log('Contact API error. HTTP: '.$httpCode.' Curl: '.$curlError.' Response: '.$apiResponse);
  }
}
?>
<!DOCTYPE html><html lang="nl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?php $filePath='title.txt';if(file_exists($filePath)){echo nl2br(htmlspecialchars(file_get_contents($filePath)));}else{echo 'Titel';} ?> - Contact</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400&family=DM+Sans:ital,wght@0,400;0,500;0,600;1,400&display=swap" rel="stylesheet"><link rel="stylesheet" href="templatemo-maison-style.css?id=<?php echo filemtime('templatemo-maison-style.css'); ?>"><link rel="stylesheet" href="zz-form-height-fix.css?id=<?php echo filemtime('zz-form-height-fix.css'); ?>"><link rel="stylesheet" href="zz-mobile-hero-title-hide.css?id=<?php echo filemtime('zz-mobile-hero-title-hide.css'); ?>"><style>.zz-form-feedback{margin:0 0 1.25rem;padding:.9rem 1rem;border:1px solid transparent;border-radius:8px;line-height:1.5;text-align:left;overflow-wrap:anywhere;scroll-margin-top:7rem}.zz-form-feedback-success{color:#155724;background:#d4edda;border-color:#c3e6cb}.zz-form-feedback-error{color:#721c24;background:#f8d7da;border-color:#f5c6cb}.zz-dynamic-content{max-width:100%;box-sizing:border-box;overflow-wrap:anywhere;word-break:break-word;overflow-x:hidden}@media(max-width:767px){.zz-dynamic-content,.zz-form-dynamic,.contact-content,.contact-form-wrapper{height:auto!important;min-height:0!important;max-height:none!important;overflow:visible!important}.form-input,.form-textarea,.form-submit{max-width:100%;box-sizing:border-box}}</style></head><body>
<header class="site-header" id="header"><div class="container"><div class="header-inner"><a href="index.php" class="navbar-brand" id="brandLogo"><img src="logo.png?id=<?php echo filemtime('logo.png'); ?>" alt="Logo" onerror="this.remove();"></a><nav class="nav-main"><a href="index.php">Startpagina</a><a href="about.php">Over ons</a><a href="service.php">Diensten</a><a href="contact.php" class="active">Contact</a></nav><button class="menu-toggle" id="menuToggle" aria-label="Menu openen/sluiten"><span></span><span></span><span></span></button></div></div></header><div class="mobile-overlay" id="mobileOverlay"></div><nav class="mobile-nav" id="mobileNav"><button class="mobile-nav-close" id="mobileNavClose">×</button><ul class="mobile-nav-links"><li><a href="index.php">Startpagina</a></li><li><a href="about.php">Over ons</a></li><li><a href="service.php">Diensten</a></li><li><a href="contact.php" class="active">Contact</a></li></ul></nav>
<?php $defaultBanner='images/maison-doree-06.jpg';$bannerFile='contactimage.txt';if(file_exists($bannerFile)){$bannerUrl=trim(file_get_contents($bannerFile));if($bannerUrl===''){$bannerUrl=$defaultBanner;}}else{$bannerUrl=$defaultBanner;} ?>
<section class="hero zz-hero"><div class="hero-content"><h1 class="heading-display hero-title zz-hero-title">Contact</h1></div><div class="hero-image"><img class="zz-hero-single-image" src="<?php echo htmlspecialchars($bannerUrl); ?>" alt="Contact"></div></section>
<section class="contact zz-form-section"><div class="container"><div class="contact-grid"><div class="contact-content"><p class="text-label">Bezoek ons atelier</p><h2 class="heading-display contact-title">Contact</h2><div class="zz-form-dynamic"><div class="zz-dynamic-content text-content"><?php $filePath='contact.txt';if(file_exists($filePath)){echo nl2br(htmlspecialchars(file_get_contents($filePath)));}else{echo '-';} ?></div></div></div><div class="contact-form-wrapper"><h3 class="form-title">Contact</h3>
<?php if($formSuccess!==''): ?><div id="form-feedback" class="zz-form-feedback zz-form-feedback-success" role="status" aria-live="polite"><?php echo htmlspecialchars($formSuccess); ?></div><?php endif; ?><?php if($formError!==''): ?><div id="form-feedback" class="zz-form-feedback zz-form-feedback-error" role="alert"><?php echo htmlspecialchars($formError); ?></div><?php endif; ?>
<form id="appointmentForm" action="" method="post"><div class="form-group"><label class="form-label" for="name">Naam</label><input type="text" id="name" name="name" class="form-input" value="<?php echo htmlspecialchars($formName,ENT_QUOTES,'UTF-8'); ?>" maxlength="150" autocomplete="name" required></div><div class="form-group"><label class="form-label" for="phone">Telefoon</label><input type="text" id="phone" name="phone" class="form-input" value="<?php echo htmlspecialchars($formPhone,ENT_QUOTES,'UTF-8'); ?>" maxlength="50" autocomplete="tel"></div><div class="form-group"><label class="form-label" for="email">E-mail</label><input type="email" id="email" name="email" class="form-input" value="<?php echo htmlspecialchars($formEmail,ENT_QUOTES,'UTF-8'); ?>" maxlength="254" autocomplete="email" required></div><div class="form-group"><label class="form-label" for="message">Bericht</label><textarea id="message" name="message" class="form-textarea" maxlength="5000" required><?php echo htmlspecialchars($formMessage); ?></textarea></div><button type="submit" class="form-submit">Verzenden</button></form><div class="zz-recaptcha-note">Deze site wordt beschermd door reCAPTCHA. Het <a href="privacy.php">privacybeleid</a> en de <a href="terms.php">algemene voorwaarden</a> van Google zijn van toepassing.</div></div></div></div></section>
<footer class="zz-site-footer"><div class="container"><div class="zz-footer-bottom"><p>Auteursrecht &copy; <?php echo date('Y'); ?> ZZpzo</p><div class="zz-footer-links"><a href="terms.php">Algemene voorwaarden</a><a href="complain.php">Klachtenportaal</a><a href="privacy.php">Privacybeleid</a></div></div></div></footer><script src="zz-maison-dynamic.js?id=<?php echo filemtime('zz-maison-dynamic.js'); ?>"></script><script>(function(){window.addEventListener('load',function(){var f=document.getElementById('form-feedback');if(f){setTimeout(function(){f.scrollIntoView({behavior:'smooth',block:'center'});},220);}});})();</script></body></html>